### ISSUE TITLE
[BUG]: saveOrFail doesnt throw QueryException

### ISSUE THREAD

**Issue by mrmoric** [dimitriBouteille/wp-orm#17]
`Database->insert() `

should throw QueryException like you do that in 

`Database->selectOne() `

because when we use

`Model->saveOrFail() `

it calls 

`Database->insert() `

internally and if if any errors occurs during query, it doesn't throw the Exception now.

**Comment by dimitriBouteille** [comment]
Hi @mrmoric 

Thanks for opening this issue. I look to fix this bug as quickly as possible, you will be informed when it is done.

Best,

**Comment by mrmoric** [comment]
@dimitriBouteille one more thing, deleteOrFail() open transaction internally and at the moment transaction is opened but it is never closed. In the query log, I see only: "[06-Mar-2024 12:55:51 UTC] START TRANSACTION;" and that's it.

It looks like WordPress can be launched with different type of tables: InnoDB, MyISAM, etc.

InnoDB tables are transactional tables.
Non-transactional tables would be e.g MyISAM.

Please check that code is working good with transactional table and non-transactional ones. I think need to add a couple of unit tests.

**Comment by mrmoric** [comment]
@dimitriBouteille you can check how this check is done in Woocommerce. Before open a transaction, they check if it's supported.

**Comment by dimitriBouteille** [comment]
@mrmoric Thanks for the information. For the function `deleteOrFail` I opened a [ticket](https://github.com/dimitriBouteille/wp-orm/issues/33) will be processed soon.

**Comment by dimitriBouteille** [comment]
@mrmoric The bug is fixed, the entire `Database` class has been refactored. The fix should be available in the next release.

If you wish, you can test on the `develop` branch :

```
composer require dbout/wp-orm dev-develop
```
