### ISSUE TITLE
Add a code example on how to create corresponding tables for models in database

### ISSUE THREAD

**Issue by mrmoric** [dimitriBouteille/wp-orm#18]
Normally we use the following code to create tables in WordPress:

```
 add_action('init', [$this, 'migrate']);


function migrate() {
        global $wpdb;

        $PluginSettings = $this->ConfigService->getPluginSettings();
        $charsetCollate = $wpdb->get_charset_collate();

        $sqlConversationTable = <<<EOD
            CREATE TABLE %s (
                  id BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
                  accountId BIGINT(20) UNSIGNED NOT NULL,
                  userId BIGINT(20) UNSIGNED NULL,
                  chatbotId BIGINT(20) UNSIGNED NOT NULL,
                  ipAddress VARCHAR(32) NULL,
                  created DATETIME NOT NULL,
                  updated DATETIME NOT NULL,
                  PRIMARY KEY (id)
                ) %s;
        EOD;

        $sqlConversationTable = sprintf(
            $sqlConversationTable, $this->ConfigService->getChatbotConversationTable(), $charsetCollate
        );

        $sqlConversationMessageTable = <<<EOD
            CREATE TABLE %s (
                  id BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
                  conversationId BIGINT(20) UNSIGNED NOT NULL,
                  author VARCHAR(32) NULL,
                  message longtext NULL,
                  created DATETIME NOT NULL,
                  updated DATETIME NOT NULL,
                  PRIMARY KEY (id)
                ) %s;
        EOD;

        $sqlConversationMessageTable = sprintf(
            $sqlConversationMessageTable, $this->ConfigService->getChatbotConversationMessageTable(), $charsetCollate
        );

        require_once( ABSPATH . 'wp-admin/includes/upgrade.php' );
        dbDelta([
            $sqlConversationTable,
            $sqlConversationMessageTable
        ]);

}
```

But how it should be done using your package? I guess we still need to use 'dbDelta' piece, but code for table creation should be done in a different way. Perhaps we have to use QueryBuilder or somehow get table schema from Models?

If we don't need to use WordPress approach but use migrations instead. Then anyway how to run these migrations only once, so it doesn't try to create tables on each page init

**Comment by axi** [comment]
I'm looking for the same answers ! Funny time synchronisation :-)
I'm new to Eloquent but it seems that the "right way" would be to use ```Illuminate\Support\Facades\Schema```  [see here](https://laravel.com/docs/5.0/schema)

```php
if (Schema::hasTable('payouts')) {
    Schema::create('payouts', static function (Blueprint $table) {
        $table->increments('id');
        $table->decimal(Payout::AMOUNT, 8, 2);
    });
}
```

Trying that led me to an "A facade root has not been set." error for now

**Comment by axi** [comment]
So I guess the question could be: how can we configure Schema to work/access our wordpress db

**Comment by mrmoric** [comment]
This package add the following dependencies to your  composer.json

```
  "require": {
    "php": ">=8.1",
    "robmorgan/phinx": "^0.12.5",
    "illuminate/database": "^10.0"
  },
```
If you want to use 

`Illuminate\Support\Facades\Schema`

you have to install [Support package](https://github.com/illuminate/support/tree/master)

but in my project I want to use minimum dependencies. Even this [wp-orm](https://github.com/dimitriBouteille/wp-orm) is quite large but its cost of using ORM with wordpress

**Comment by axi** [comment]
```illuminate/support``` is a required dependency of  ```illuminate/database```, already installed then

**Comment by axi** [comment]
Lol, [chatGPT helped](https://i.imgur.com/NxSE7Zr.png)

**Comment by mrmoric** [comment]
Need to `getDefaultSchemaGrammar` to `Dbout\WpOrm\Orm\Database`
It's strange but this method is not added to the `ConnectionInterface` but they add it for example in `Illuminate\Database\MySqlConnection`

If such method will be added then we can set the connection in Facade `Illuminate\Support\Facades\Schema`:

  
```
    public static function connection($name)
    {
        return static::$app['db']->connection($name)->getSchemaBuilder();
    }
```

**Comment by dimitriBouteille** [comment]
Bonjour @mrmoric  et @axi 

As indicated by @mrmoric , the package contains a dependency to `robmorgan/phinx` that allows you to simply create database migrations.

This tool works very simply because you just need to create a `config-phinx.php` configuration file at the root of your project and then create the migrations. An example of this configuration file can be found here: https://github.com/dimitriBouteille/wp-orm/blob/master/doc/migration.md#migration 

If you use a tool other than Bedrock, I invite you to propose an MR to explain how to use the tool on another Framework than Bedrock so that other people can enjoy it:)

Here is an example of a migration that adds a column:

```php
declare(strict_types=1);

use Phinx\Migration\AbstractMigration;

final class V20210812221926 extends AbstractMigration
{
    /**
     * Change Method.
     *
     * Write your reversible migrations using this method.
     *
     * More information on writing migrations is available here:
     * https://book.cakephp.org/phinx/0/en/migrations.html#the-change-method
     *
     * Remember to call "create()" or "update()" and NOT "save()" when working
     * with the Table class.
     */
    public function change(): void
    {
        $table = $this->table(\MyModel::table());
        if ($table->exists()) {
            $table
                ->addColumn(\MyModel::MY_PROPERTY, 'string', ['null' => true])
                ->update();
        }
    }
}
```

You can look this documentation for more information: https://book.cakephp.org/phinx/0/en/migrations.html#

---

@axi The dependency to the `robmorgan/phinx` package is temporary since the objective is to remove this dependency in order to use `\Illuminate\Support\Facades\Schema`.

This migration will take some time, I plan to work on this topic in April or May.

---

I remain available if you need help using Phinx or if you have ideas to improve this package :)

**Comment by dimitriBouteille** [comment]
I close this issue, I opened the following issues :)

-  https://github.com/dimitriBouteille/wp-orm/issues/27 
- https://github.com/dimitriBouteille/wp-orm/issues/28
