### ISSUE TITLE
[BUG]: Event is not fired

### ISSUE THREAD

**Issue by mrmoric** [dimitriBouteille/wp-orm#73]
Simply create two models like:

Profile and User.

User hasOne Profile

Then I would like to remove user's profile automatically when delete the user.
Normally it should work like this:

`User {
    public function account(): HasOne
    {
        return $this->hasOne(Account::class);
    }
    
        protected static function booted(): void
    {
        parent::booted();
        static::deleted(function (User $User) {
            $User ->getAccount()?->delete();
        });
    }
}`

So in client code I should be able to use User and related profile using simple command:

`
$User ->delete();
`

Unfortunately, ` static::deleted` is not called.

**Comment by dimitriBouteille** [comment]
Hi @mrmoric 

Thanks for the details. I look to fix this bug as quickly as possible, you will be informed when it is done.

Best,
