### ISSUE TITLE
app.ERROR: ErrorException: Call to undefined function wp_orm_get_phinx_config()

### ISSUE THREAD

**Issue by arnaudbagnis** [dimitriBouteille/wp-orm#8]
i have a error when il try to create migration 

my config-phinx.php

```
<?php

use Roots\WPConfig\Config;

/**
 * And load wordpress
 */
require 'web/wp/wp-load.php';

/**
 * Export phinx config
 */


return wp_orm_get_phinx_config([
    'migrations_path' => 'database/migrations',
    'db_user' => Config::get('DB_USER'),
    'db_password' => Config::get('DB_PASSWORD'),
    'db_name' => Config::get('DB_NAME'),
    'db_host' => Config::get('DB_HOST'),
]);
```

**Comment by dimitriBouteille** [comment]
Hello @arnaudbagnis ,

- Does the following file exist `vendor/dbout/wp-orm/src/includes/migrations.php` ? 
- How do you run the migration ?

**Comment by arnaudbagnis** [comment]
I run migration in the root project (i use Bedrock) but I dont have migrations.php in my vendor

**Comment by arnaudbagnis** [comment]
My error when I start 
`ErrorException: Call to undefined function wp_orm_get_phinx_config()`

**Comment by arnaudbagnis** [comment]
Solved by installing from master branch 

`composer require dbout/wp-orm dev-master`
